# Generated by Django 5.0.6 on 2026-09-25 13:48

import account.models
import django.core.validators
import media_bank.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_fix_last_login_auto_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=account.models.profile_picture_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
    ]
