# Generated by Django 5.0.6 on 2026-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50)),
                ('primary_50', models.CharField(default='#EFF6FF', max_length=7)),
                ('primary_100', models.CharField(default='#DBEAFE', max_length=7)),
                ('primary_200', models.CharField(default='#BFDBFE', max_length=7)),
                ('primary_300', models.CharField(default='#93C5FD', max_length=7)),
                ('primary_400', models.CharField(default='#60A5FA', max_length=7)),
                ('primary_500', models.CharField(default='#3B82F6', max_length=7)),
                ('primary_600', models.CharField(default='#2563EB', max_length=7)),
                ('primary_700', models.CharField(default='#1D4ED8', max_length=7)),
                ('primary_800', models.CharField(default='#1E40AF', max_length=7)),
                ('primary_900', models.CharField(default='#1E3A8A', max_length=7)),
                ('accent_400', models.CharField(default='#FBBF24', max_length=7)),
                ('accent_500', models.CharField(default='#F59E0B', max_length=7)),
                ('accent_600', models.CharField(default='#D97706', max_length=7)),
                ('soft_bg', models.CharField(default='#F0F9FF', max_length=7, verbose_name='Fondo global (modo claro)')),
            ],
            options={
                'verbose_name': 'Tema del Sitio',
                'verbose_name_plural': 'Tema del Sitio',
            },
        ),
    ]
