# Generated by Django 5.0.6 on 2026-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bulonera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='footer_bg',
            field=models.CharField(default='#0F172A', max_length=7, verbose_name='Footer — Fondo'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='footer_text',
            field=models.CharField(default='#CBD5E1', max_length=7, verbose_name='Footer — Texto'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='navbar_bg',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Navbar — Fondo'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='navbar_text',
            field=models.CharField(default='#0F172A', max_length=7, verbose_name='Navbar — Texto e íconos'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='subbar_from',
            field=models.CharField(default='#1D4ED8', max_length=7, verbose_name='Barra de Título — Color inicial del gradiente'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='subbar_to',
            field=models.CharField(default='#1E3A8A', max_length=7, verbose_name='Barra de Título — Color final del gradiente'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='topbar_text',
            field=models.CharField(default='#475569', max_length=7, verbose_name='Topbar — Texto'),
        ),
    ]
