# Generated by Django 5.0.6 on 2026-04-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bulonera', '0002_sitetheme_footer_bg_sitetheme_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='footer_opacity',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Footer — Opacidad (%)'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='navbar_opacity',
            field=models.PositiveSmallIntegerField(default=100, help_text='0 (transparente) a 100 (sólido)', verbose_name='Navbar — Opacidad (%)'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='subbar_opacity',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Barra de Título — Opacidad (%)'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='subbar_from',
            field=models.CharField(default='#1D4ED8', max_length=7, verbose_name='Barra de Título — Color inicial'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='subbar_to',
            field=models.CharField(default='#1E3A8A', max_length=7, verbose_name='Barra de Título — Color final'),
        ),
    ]
