# Generated by Django 5.0.6 on 2026-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bulonera', '0003_sitetheme_footer_opacity_sitetheme_navbar_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='bestseller_bg',
            field=models.CharField(default='#F0F9FF', max_length=7, verbose_name='Lo más vendido — Fondo'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='bestseller_opacity',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Lo más vendido — Opacidad (%)'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='quickcat_bg',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Categorías Rápidas — Fondo'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='quickcat_opacity',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Categorías Rápidas — Opacidad (%)'),
        ),
    ]
