# Generated by Django 5.0.6 on 2026-04-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bulonera', '0004_sitetheme_bestseller_bg_sitetheme_bestseller_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetheme',
            name='bestseller_bg',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Lo más vendido — Fondo'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='quickcat_bg',
            field=models.CharField(default='#F5F5F7', max_length=7, verbose_name='Categorías Rápidas — Fondo'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='soft_bg',
            field=models.CharField(default='#F5F5F7', max_length=7, verbose_name='Fondo global (modo claro)'),
        ),
    ]
