# Generated by Django 5.0.6 on 2026-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bulonera', '0005_alter_sitetheme_bestseller_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_100',
            field=models.CharField(default='#C5D9ED', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_200',
            field=models.CharField(default='#9AC1F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_300',
            field=models.CharField(default='#7BAEE0', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_400',
            field=models.CharField(default='#5B95D0', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_50',
            field=models.CharField(default='#E2ECF6', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_500',
            field=models.CharField(default='#4A6FA5', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_600',
            field=models.CharField(default='#3A5F8F', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_700',
            field=models.CharField(default='#2A4F79', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_800',
            field=models.CharField(default='#1B3A5C', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_900',
            field=models.CharField(default='#122840', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='subbar_from',
            field=models.CharField(default='#1B3A5C', max_length=7, verbose_name='Barra de Título — Color inicial'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='subbar_to',
            field=models.CharField(default='#122840', max_length=7, verbose_name='Barra de Título — Color final'),
        ),
    ]
