# Generated by Django 5.0.6 on 2025-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productgallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grado/Dureza'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='norm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Norma'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='product',
            name='thread_formats',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formatos de rosca'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
