# Generated by Django 5.0.6 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_faqcategory_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='google_category',
            field=models.CharField(blank=True, help_text='Categoría de Google Merchant (ej: Hardware > Fasteners > Bolts)', max_length=255, null=True),
        ),
    ]
