# Generated by Django 5.0.6 on 2026-04-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_bank', '0002_imageasset_image_type_alter_imageasset_file'),
        ('store', '0005_product_google_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen del carrusel (desde Banco de Imágenes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='media_bank.imageasset'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen principal del producto (desde Banco de Imágenes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='media_bank.imageasset'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen de galería (desde Banco de Imágenes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='media_bank.imageasset'),
        ),
    ]
