# Generated by Django 5.0.6 on 2026-04-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_image_subcategory_image_asset'),
        ('store', '0006_carouselimage_image_asset_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Título visible en la Home (ej: 'Los más vendidos')", max_length=150)),
                ('section_type', models.CharField(choices=[('hero', 'Carrusel Hero (Banners Principales)'), ('quick_access', 'Acceso Rápido (Iconos: pagos, envíos, etc.)'), ('product_carousel', 'Carrusel de Productos'), ('banner_landing', 'Banner Landing (1 imagen ancho completo)'), ('banner_double', 'Banner Doble (2 imágenes lado a lado)'), ('banner_triple', 'Banner Triple (3 imágenes en fila)'), ('categories', 'Grid de Categorías'), ('how_to_buy', 'Sección Cómo Comprar')], max_length=20)),
                ('source_type', models.CharField(blank=True, choices=[('bestsellers', 'Más Vendidos'), ('most_searched', 'Más Buscados'), ('by_category', 'Por Categoría'), ('on_sale', 'En Oferta'), ('newest', 'Más Recientes'), ('custom', 'Selección Manual')], help_text='Fuente de productos (solo para carruseles de productos)', max_length=20, null=True)),
                ('max_products', models.PositiveSmallIntegerField(default=12, help_text='Cantidad máxima de productos a mostrar')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición (menor = más arriba)')),
                ('is_active', models.BooleanField(default=True)),
                ('highlight_color', models.CharField(blank=True, help_text="Color de fondo especial (ej: 'bg-amber-50' para ofertas). Dejar vacío = default.", max_length=30)),
                ('category', models.ForeignKey(blank=True, help_text="Categoría fuente (solo si source_type = 'by_category')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
            options={
                'verbose_name': 'Sección de la Home',
                'verbose_name_plural': 'Secciones de la Home',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título interno (no visible al público)', max_length=150)),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para SEO y accesibilidad', max_length=200)),
                ('image_desktop', models.ImageField(help_text='Imagen para desktop (ver guía de tamaños abajo)', upload_to='photos/banners/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Imagen para mobile (opcional, se usa desktop si vacío)', null=True, upload_to='photos/banners/')),
                ('url', models.CharField(blank=True, help_text='URL manual (máxima prioridad). Para blogs, redes sociales, páginas externas.', max_length=500)),
                ('link_params', models.CharField(blank=True, help_text='Filtros adicionales para la URL. Ej: ?promo=active, ?brand=stanley', max_length=300)),
                ('open_new_tab', models.BooleanField(default=False, help_text='Abrir en pestaña nueva (recomendado para enlaces externos)')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('link_category', models.ForeignKey(blank=True, help_text='Redirigir a la tienda filtrada por esta categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners', to='category.category')),
                ('link_product', models.ForeignKey(blank=True, help_text='Redirigir a este producto específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners', to='store.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='store.homesection')),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Orden dentro del carrusel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sections', to='store.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_section_products', to='store.homesection')),
            ],
            options={
                'verbose_name': 'Producto de la Sección',
                'verbose_name_plural': 'Productos de la Sección',
                'ordering': ['position'],
                'unique_together': {('section', 'product')},
            },
        ),
    ]
