# Generated by Django 5.0.6 on 2026-04-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_create_initial_home_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, help_text="Imagen directa (legacy). Usar 'Imagen del banco' es preferible.", null=True, upload_to='photos/carousel'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Carrusel Hero (Banners Principales)'), ('quick_access', 'Acceso Rápido (Iconos: pagos, envíos, etc.)'), ('product_carousel', 'Carrusel de Productos'), ('banner_landing', 'Banner Landing (1 imagen ancho completo)'), ('banner_double', 'Banner Doble (2 imágenes lado a lado)'), ('banner_triple', 'Banner Triple (3 imágenes en fila)'), ('categories_featured', 'Grid de Categorías Destacadas'), ('categories_carousel', 'Carrusel de Categorías'), ('how_to_buy', 'Sección Cómo Comprar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='source_type',
            field=models.CharField(blank=True, choices=[('bestsellers', 'Más Vendidos'), ('most_searched', 'Más Buscados'), ('by_category', 'Por Categoría'), ('on_sale', 'En Oferta'), ('newest', 'Más Recientes'), ('custom', 'Selección Manual'), ('categories_featured', 'Categorías Destacadas'), ('categories_carousel', 'Carrusel de Categorías')], help_text='Fuente de productos (solo para carruseles de productos)', max_length=20, null=True),
        ),
    ]
