# Generated by Django 5.0.6 on 2026-04-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_bank', '0003_alter_imageasset_image_type'),
        ('store', '0009_alter_carouselimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='image_desktop_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen Desktop desde el Banco', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners_desktop', to='media_bank.imageasset'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='image_mobile_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen Mobile desde el Banco (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners_mobile', to='media_bank.imageasset'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image_desktop',
            field=models.ImageField(blank=True, help_text='[LEGACY] Imagen para desktop (usar Banco de Imágenes preferentemente)', null=True, upload_to='photos/banners/'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='[LEGACY] Imagen para mobile (usar Banco de Imágenes preferentemente)', null=True, upload_to='photos/banners/'),
        ),
    ]
