# Generated by Django 5.0.6 on 2026-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_promobanner_image_desktop_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Carrusel Hero (Banners Principales)'), ('quick_access', 'Acceso Rápido (Iconos: pagos, envíos, etc.)'), ('trust_bar', 'Barra de Confianza'), ('product_carousel', 'Carrusel de Productos'), ('banner_landing', 'Banner Landing (1 imagen ancho completo)'), ('banner_double', 'Banner Doble (2 imágenes lado a lado)'), ('banner_triple', 'Banner Triple (3 imágenes en fila)'), ('categories_featured', 'Grid de Categorías Destacadas'), ('categories_carousel', 'Carrusel de Categorías'), ('how_to_buy', 'Sección Cómo Comprar')], max_length=20),
        ),
    ]
