# Generated by Django 5.0.6 on 2026-04-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_bank', '0003_alter_imageasset_image_type'),
        ('store', '0011_alter_homesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Imagen mobile directa (legacy). Usar Banco de Imágenes preferentemente.', null=True, upload_to='photos/carousel'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='image_mobile_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen para mobile (Art Direction). Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_items_mobile', to='media_bank.imageasset'),
        ),
    ]
