# Generated by Django 5.0.6 on 2026-04-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_carouselimage_image_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='show_title',
            field=models.BooleanField(default=True, help_text='¿Mostrar el título y fondo oscuro sobre la imagen? (Desactivar si la imagen ya tiene el texto dibujado)'),
        ),
    ]
