# Generated by Django 5.0.6 on 2026-04-15 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_bank', '0003_alter_imageasset_image_type'),
        ('store', '0013_carouselimage_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='image_large_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen Monitor Grande (≥1536px) desde el Banco. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_items_large', to='media_bank.imageasset'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='image_tablet_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen Tablet (640–1023px) desde el Banco. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_items_tablet', to='media_bank.imageasset'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='image_large_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen Monitor Grande (≥1536px) desde el Banco. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners_large', to='media_bank.imageasset'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='image_tablet_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen Tablet (640–1023px) desde el Banco. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_banners_tablet', to='media_bank.imageasset'),
        ),
    ]
