# Generated by Django 5.0.6 on 2026-04-17 14:03

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_carouselimage_image_large_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, help_text="Imagen directa (legacy). Usar 'Imagen del banco' es preferible.", null=True, upload_to=store.models.store_carousel_image_path),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Imagen mobile directa (legacy). Usar Banco de Imágenes preferentemente.', null=True, upload_to=store.models.store_carousel_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to=store.models.store_product_image_path),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=250, upload_to=store.models.store_product_image_path),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image_desktop',
            field=models.ImageField(blank=True, help_text='[LEGACY] Imagen para desktop (usar Banco de Imágenes preferentemente)', null=True, upload_to=store.models.store_banner_image_path),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='[LEGACY] Imagen para mobile (usar Banco de Imágenes preferentemente)', null=True, upload_to=store.models.store_banner_image_path),
        ),
    ]
