# Generated by Django 5.0.6 on 2026-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_carouselimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=155, null=True, verbose_name='Meta descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta título'),
        ),
    ]
