# Generated by Django 5.0.6 on 2026-06-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_homesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='cta_text',
            field=models.CharField(blank=True, default='', help_text="Texto del llamado a la acción (solo para 'Banda CTA'). Ej: ¿Necesitás cotizar? Consultanos sin compromiso.", max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Carrusel Hero (Banners Principales)'), ('quick_access', 'Acceso Rápido (Iconos: pagos, envíos, etc.)'), ('trust_bar', 'Barra de Confianza'), ('product_carousel', 'Carrusel de Productos'), ('banner_landing', 'Banner Landing (1 imagen ancho completo)'), ('banner_double', 'Banner Doble (2 imágenes lado a lado)'), ('banner_triple', 'Banner Triple (3 imágenes en fila)'), ('categories_featured', 'Grid de Categorías Destacadas'), ('categories_carousel', 'Carrusel de Categorías'), ('google_reviews', 'Reseñas de Google (Widget Embed)'), ('how_to_buy', 'Sección Cómo Comprar'), ('cta_band', 'Banda CTA (Llamada a la Acción)')], max_length=20),
        ),
    ]
