# Generated by Django 5.0.6 on 2026-09-25 14:22

import django.core.validators
import media_bank.upload_utils
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_create_initial_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, help_text="Imagen directa (legacy). Usar 'Imagen del banco' es preferible.", null=True, upload_to=store.models.store_carousel_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Imagen mobile directa (legacy). Usar Banco de Imágenes preferentemente.', null=True, upload_to=store.models.store_carousel_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to=store.models.store_product_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=250, upload_to=store.models.store_product_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image_desktop',
            field=models.ImageField(blank=True, help_text='[LEGACY] Imagen para desktop (usar Banco de Imágenes preferentemente)', null=True, upload_to=store.models.store_banner_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='[LEGACY] Imagen para mobile (usar Banco de Imágenes preferentemente)', null=True, upload_to=store.models.store_banner_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
    ]
