# Generated by Django 5.0.6 on 2026-10-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_carouselimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactivo oculta el tag de los filtros')),
            ],
            options={
                'verbose_name': 'Tag de Producto',
                'verbose_name_plural': 'Tags de Productos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.producttag'),
        ),
    ]
