[pytest]
DJANGO_SETTINGS_MODULE = web_bulonera.settings.test
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short --strict-markers -v --import-mode=importlib
markers =
    integration: Tests que requieren acceso a BD
    smoke: Tests rápidos de humo
    slow: Tests lentos
testpaths = .
