# Generated by Django 5.0.6 on 2026-04-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Archivo de imagen', upload_to='photos/products/original/')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo (auto-generado del archivo si vacío)', max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para SEO', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Banco de Imágenes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
