# Generated by Django 5.0.6 on 2026-04-09 21:16

import media_bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='image_type',
            field=models.CharField(choices=[('product', 'Producto'), ('category', 'Categoría'), ('subcategory', 'Subcategoría'), ('carousel', 'Carrusel')], default='product', help_text='Tipo de imagen', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(help_text='Archivo de imagen', upload_to=media_bank.models.image_asset_upload_path),
        ),
    ]
