# Generated by Django 5.0.6 on 2026-04-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_bank', '0002_imageasset_image_type_alter_imageasset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='image_type',
            field=models.CharField(choices=[('product', 'Producto'), ('category', 'Categoría'), ('subcategory', 'Subcategoría'), ('carousel', 'Carrusel'), ('banner', 'Banner')], default='product', help_text='Tipo de imagen', max_length=20),
        ),
    ]
