# Generated by Django 5.0.6 on 2026-09-24 13:18

import django.core.validators
import media_bank.models
import media_bank.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_bank', '0003_alter_imageasset_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(help_text='Archivo de imagen (JPG, PNG, WEBP, GIF; máx 10 MB)', upload_to=media_bank.models.image_asset_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), media_bank.upload_utils.validate_image_file]),
        ),
    ]
