# Generated by Django 5.0.6 on 2025-04-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_featuredcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, default='fa-folder', max_length=50),
        ),
    ]
