# Generated by Django 5.0.6 on 2025-04-19 15:57

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to=category.models.category_image_path),
        ),
    ]
