# Generated by Django 5.0.6 on 2025-04-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_class',
        ),
    ]
