# Generated by Django 5.0.6 on 2026-09-20 01:17

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoption',
            name='name',
            field=models.CharField(max_length=100, validators=[contact.models.validate_no_crlf], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactoption',
            name='subject',
            field=models.CharField(max_length=200, validators=[contact.models.validate_no_crlf], verbose_name='Asunto'),
        ),
    ]
