# Generated by Django 5.0.6 on 2025-06-13 13:04

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=category.models.subcategory_image_path),
        ),
    ]
