# Generated by Django 5.0.6 on 2026-04-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory_image'),
        ('media_bank', '0002_imageasset_image_type_alter_imageasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen de categoría (desde Banco de Imágenes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='media_bank.imageasset'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Imagen de subcategoría (desde Banco de Imágenes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='media_bank.imageasset'),
        ),
    ]
