# Generated by Django 5.0.6 on 2026-04-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_image_subcategory_image_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description (máx 155 caracteres)', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (máx 60 caracteres)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description (máx 155 caracteres)', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (máx 60 caracteres)', max_length=60, null=True),
        ),
    ]
