# Generated by Django 5.2.13 on 2026-04-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_meta_description_category_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rich_description',
            field=models.TextField(blank=True, help_text="Texto HTML para SEO de categoría. Incluir: tabla de medidas, aplicaciones, keywords long-tail. Ejemplo: 'Nuestros bulones G5 están disponibles en medidas desde 1/4 hasta 1.1/2 pulgadas...'", verbose_name='Descripción SEO Maestra'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='rich_description',
            field=models.TextField(blank=True, help_text='Texto HTML para SEO de subcategoría.', verbose_name='Descripción SEO Maestra'),
        ),
    ]
