# Generated by Django 5.0.6 on 2026-04-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_meta_description_category_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description (máx 160 caracteres)', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (máx 70 caracteres)', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description (máx 160 caracteres)', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (máx 70 caracteres)', max_length=70, null=True),
        ),
    ]
