# Generated by Django 5.0.6 on 2026-06-20 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_rich_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('item_type', models.CharField(choices=[('category', 'Categoría del sistema'), ('custom', 'Link personalizado'), ('mega_menu', 'Mega-menú de categorías')], max_length=20)),
                ('custom_url', models.CharField(blank=True, help_text="Solo si el tipo es 'Link personalizado' (ej: /blog/ o URL completa)", max_length=255)),
                ('icon', models.CharField(blank=True, help_text="Nombre de icono Lucide (ej: 'newspaper')", max_length=50)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, help_text="Solo si el tipo es 'Categoría del sistema'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar_items', to='category.category')),
            ],
            options={
                'verbose_name': 'Item de Navegación',
                'verbose_name_plural': 'Items de Navegación',
                'ordering': ['position'],
            },
        ),
    ]
