# Generated by Django 5.0.6 on 2026-09-25 14:22

import category.models
import django.core.validators
import media_bank.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_navbaritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to=category.models.category_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=category.models.subcategory_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), media_bank.upload_utils.validate_image_file]),
        ),
    ]
