# Generated by Django 5.2.13 on 2026-04-25 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_bank', '0003_alter_imageasset_image_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tag', max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del artículo', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL amigable (auto-generado)', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Contenido del artículo (HTML permitido)')),
                ('excerpt', models.CharField(blank=True, help_text='Resumen corto para previews y meta description', max_length=300)),
                ('post_type', models.CharField(choices=[('article', 'Artículo Original'), ('social_repost', 'Repost de Red Social')], default='article', help_text='Tipo de post', max_length=20)),
                ('image_alt', models.CharField(blank=True, help_text='Texto alternativo de la imagen', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='Meta título para SEO (máx 70 caracteres)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta descripción para SEO (máx 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Última modificación')),
                ('published_date', models.DateTimeField(blank=True, help_text='Fecha de publicación', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='¿Está publicado?')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Número de vistas')),
                ('author', models.ForeignKey(help_text='Autor del post (admin)', on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Imagen destacada (desde Banco de Imágenes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='media_bank.imageasset')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags para categorizar el post', related_name='posts', to='blog.posttag')),
            ],
            options={
                'verbose_name': 'Artículo de Blog',
                'verbose_name_plural': 'Artículos de Blog',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)')], help_text='Red social de origen', max_length=20)),
                ('original_url', models.URLField(help_text='URL del post original en la red social')),
                ('embed_code', models.TextField(blank=True, help_text='Código HTML del embed (iframe)')),
                ('embed_url', models.URLField(blank=True, help_text='URL del embed (si aplica)')),
                ('captured_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de captura del embed')),
                ('post', models.OneToOneField(help_text='Post al que pertenece este metadata', on_delete=django.db.models.deletion.CASCADE, related_name='social_metadata', to='blog.post')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-published_date'], name='blog_post_is_publ_412f67_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type'], name='blog_post_post_ty_ffe491_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmetadata',
            unique_together={('post', 'platform')},
        ),
    ]
