# Generated by Django 5.2.13 on 2026-04-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable (auto-generado desde el título)', max_length=200, unique=True),
        ),
    ]
