# Generated by Django 5.2.13 on 2026-04-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmetadata',
            unique_together=set(),
        ),
    ]
