# Generated by Django 5.0.6 on 2026-09-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_socialmetadata_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt', 'Português')], db_index=True, help_text='Código del idioma (en, pt)', max_length=5)),
                ('title', models.CharField(help_text='Título traducido del artículo', max_length=200)),
                ('slug', models.SlugField(help_text='Slug SEO en el idioma correspondiente (ej: grade-8-bolts-guide)', max_length=200)),
                ('content', models.TextField(help_text='Contenido completo del artículo en este idioma (HTML/CKEditor)')),
                ('excerpt', models.CharField(blank=True, help_text='Resumen traducido para previews y meta description', max_length=300)),
                ('image_alt', models.CharField(blank=True, help_text='Texto alternativo de la imagen en este idioma', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='Meta título traducido para SEO (máx 70 caracteres)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta descripción traducida para SEO (máx 160 caracteres)', max_length=160)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(help_text='Artículo principal al que pertenece esta traducción', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post')),
            ],
            options={
                'verbose_name': 'Traducción de Artículo',
                'verbose_name_plural': 'Traducciones de Artículos',
                'indexes': [models.Index(fields=['language', 'slug'], name='blog_posttr_languag_57baa4_idx')],
                'unique_together': {('language', 'slug'), ('post', 'language')},
            },
        ),
    ]
