"""
Django settings for bulonera project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # Cargar variables de entorno desde .env
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Determinar si estamos en desarrollo o producción
DEBUG = env.bool('DEBUG', default=True)  # Ahora en desarrollo. Cambiar a False en producción.

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    
    #LOCAL_APPS
    'bulonera',
    'category',
    'account',
    'store',
    'cart',
    'orders',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'bulonera.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(BASE_DIR), 'bulonera/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bulonera.context_processors.meta_settings',
                'category.context_processors.menu_links',
                'cart.context_processors.counter',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'bulonera.wsgi.application'

AUTH_USER_MODEL = 'account.Account'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),  # Debes crear esta base de datos primero
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),  # La contraseña que estableciste para root
        'HOST': env('DB_HOST', default='localhost'),  # o 127.0.0.1
        'PORT': env('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'collation': 'utf8mb4_spanish_ci',
            'init_command': "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_spanish_ci';"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Ruta completa a la carpeta staticfiles cuando estemos en producción.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Ruta completa a la carpeta static
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR : 'danger',
}
""" Cuando cambie a producción, descomentar las siguientes líneas para mayor seguridad.
# Configuración de seguridad adicional
SECURE_HSTS_SECONDS = 31536000  # 1 año
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ['https://tu_dominio,com', 'https://www.tu_dominio,com']
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

"""

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# session timeout settings:
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_SECONDS = 3600 # session expiration is 1 hour
SESSION_TIMEOUT_REDIRECT = 'home'

# Moneda que usas en tu tienda
CURRENCY = 'ARS'

# Número de WhatsApp (formato internacional, sin +)
WHATSAPP_NUMBER = env('WHATSAPP_NUMBER')

# Configuración específica según entorno
if DEBUG: # Ahora DEBUG = true ---> Estoy en desarrollo. 
    # Entorno de desarrollo
    SITE_URL = env('SITE_URL') # SITE_URL
    # Desactivar Meta Pixel en desarrollo
    META_PIXEL_ENABLED = False
    META_PIXEL_ID = env('META_PIXEL_ID')  # ID real, pero no se usará en desarrollo
    
    # Configuración para envío de emails
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('MAILTRAP_HOST')
    EMAIL_PORT = env('MAILTRAP_PORT')
    EMAIL_HOST_USER = env('MAILTRAP_USER')
    EMAIL_HOST_PASSWORD = env('MAILTRAP_PASSWORD')
    EMAIL_USE_TLS = True

    DEFAULT_FROM_EMAIL = env('EMAIL_TO_SEND_MESSAGES') #'tu@email.com'

    # Email para recibir los mensajes de contacto   
    CONTACT_EMAIL = env('EMAIL_TO_RECEIVE_MESSAGES') #'tucorreo@dominio.com'
    
else: #Cuando cambie a DEBUG = false ----> Cambio a Producción.
    # Entorno de producción
    SITE_URL = env('SITE_URL') #SITE_URL
    META_PIXEL_ENABLED = True
    META_PIXEL_ID = env('META_PIXEL_ID') #Buscar tu pixel ID de facebook
    
            # Configuración para envío de emails
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('MAILTRAP_HOST')
    EMAIL_PORT = env('MAILTRAP_PORT')
    EMAIL_HOST_USER = env('MAILTRAP_USER')
    EMAIL_HOST_PASSWORD = env('MAILTRAP_PASSWORD')
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False

    DEFAULT_FROM_EMAIL = env('EMAIL_TO_SEND_MESSAGES') #'tu@email.com'

    # Email para recibir los mensajes de contacto
    CONTACT_EMAIL = env('EMAIL_TO_RECEIVE_MESSAGES') #'tucorreo@dominio.com'

""" Cuando cambie a producción, descomentar las siguientes líneas
# Logging Configuration
from pathlib import Path

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/var/www/bulonera/logs/django.log',
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'store': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
# Asegurarse de que el directorio de logs existe con los permisos correctos
LOG_DIR = '/var/www/bulonera/logs'
try:
    Path(LOG_DIR).mkdir(parents=True, exist_ok=True)
    log_file = Path(LOG_DIR) / 'django.log'
    log_file.touch(exist_ok=True)
except Exception as e:
    print(f"Error creating log directory or file: {e}") 
"""