"""
Django settings for bulonera project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # Cargar variables de entorno desde .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Determinar si estamos en desarrollo o producción
DEBUG = True  # Ahora en desarrollo. Cambiar a False en producción.

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #LOCAL_APPS
    'category',
    'account',
    'store',
    'cart',
    'orders',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'bulonera.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(BASE_DIR), 'bulonera/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bulonera.context_processors.meta_settings',
                'category.context_processors.menu_links',
                'cart.context_processors.counter',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'bulonera.wsgi.application'

AUTH_USER_MODEL = 'account.Account'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Ruta completa a la carpeta static
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR /'media'

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR : 'danger',
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# session timeout settings:
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_SECONDS = 3600 #session expiration is 1 hour
SESSION_TIMEOUT_REDIRECT = 'account/login'

# Moneda que usas en tu tienda
CURRENCY = 'USD'

# Número de WhatsApp (formato internacional, sin +)
WHATSAPP_NUMBER = '5493624733431'  # Ejemplo para Argentina

# Configuración específica según entorno
if DEBUG: #Ahora DEBUG = true ---> Estoy en desarrollo. 
    # Entorno de desarrollo
    SITE_URL = 'http://127.0.0.1:8000/'#SITE_URL
    # Desactivar Meta Pixel en desarrollo
    META_PIXEL_ENABLED = False
    META_PIXEL_ID = '406099791293899'  # ID real, pero no se usará en desarrollo
    
    # Configuración para envío de emails
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('MAILTRAP_HOST')
    EMAIL_PORT = os.getenv('MAILTRAP_PORT')
    EMAIL_HOST_USER = os.getenv('MAILTRAP_USER')
    EMAIL_HOST_PASSWORD = os.getenv('MAILTRAP_PASSWORD')
    EMAIL_USE_TLS = True

    DEFAULT_FROM_EMAIL = 'melafrancom@gmail.com'#'tu@email.com'

    # Email para recibir los mensajes de contacto   
    CONTACT_EMAIL = 'ffea05f34135ba@inbox.mailtrap.io'#'tucorreo@dominio.com'
    
else: #Cuando cambie a DEBUG = false ----> Cambio a Producción.
    # Entorno de producción
    SITE_URL = 'https://buloneraalvear.com/'#SITE_URL
    META_PIXEL_ENABLED = True
    META_PIXEL_ID = '406099791293899'#Buscar tu pixel ID de facebook
    
            # Configuración para envío de emails
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('MAILTRAP_HOST')
    EMAIL_PORT = os.getenv('MAILTRAP_PORT')
    EMAIL_HOST_USER = os.getenv('MAILTRAP_USER')
    EMAIL_HOST_PASSWORD = os.getenv('MAILTRAP_PASSWORD')
    EMAIL_USE_TLS = True

    DEFAULT_FROM_EMAIL = 'melafrancom@gmail.com'#'tu@email.com'

    # Email para recibir los mensajes de contacto
    CONTACT_EMAIL = 'tucorreo@dominio.com'#'tucorreo@dominio.com'



