# Generated by Django 5.0.6 on 2025-05-14 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('images', models.ImageField(blank=True, upload_to='photos/products')),
                ('image_alt', models.CharField(blank=True, help_text='Texto alternativo de la imagen principal (SEO)', max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('sold_count', models.IntegerField(default=0)),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='En oferta')),
                ('sale_price', models.FloatField(blank=True, null=True, verbose_name='Precio de oferta')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, verbose_name='Porcentaje de descuento')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado'), ('refurbished', 'Reacondicionado')], default='new', max_length=20)),
                ('gtin', models.CharField(blank=True, max_length=50, null=True)),
                ('mpn', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta título')),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True, verbose_name='Meta descripción')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabras clave (separadas por comas)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subcategories', models.ManyToManyField(blank=True, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/carousel')),
                ('description', models.TextField(blank=True, help_text='Descripción de la imagen (opcional)')),
                ('url', models.CharField(blank=True, help_text='URL a la que redirige al hacer clic', max_length=255, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='Asociar con un producto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=250, upload_to='store/products')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('talla', 'talla')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Búsqueda de Producto',
                'verbose_name_plural': 'Búsquedas de Productos',
                'unique_together': {('product', 'session_key'), ('product', 'user')},
            },
        ),
    ]
