# Generated by Django 5.0.6 on 2025-05-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productgallery_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Texto alternativo de la imagen principal (SEO)', max_length=255),
        ),
    ]
